# Generated by Django 5.2.4 on 2025-07-15 18:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='first_name',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_name',
            field=models.CharField(default='Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='supporting_documents',
            field=models.CharField(choices=[('cv', 'Curriculum Vitae'), ('cover_letter', 'Cover Letter'), ('resume', 'Resume'), ('recommendation', 'Recommendation Letter')], default='cv', help_text='Select the type of document being uploaded', max_length=50),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='year_of_completion',
            field=models.PositiveIntegerField(default=2020),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='education_level',
            field=models.CharField(choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelor', 'Bachelor’s Degree'), ('masters', 'Master’s Degree'), ('phd', 'PhD')], default='high_school', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
