# Generated by Django 6.0.7 on 2026-07-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='field',
            field=models.CharField(choices=[('general', 'General'), ('it', 'IT'), ('accounting', 'Accounting'), ('nursing', 'Nursing'), ('education', 'Education'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('healthcare', 'Healthcare'), ('law', 'Law'), ('other', 'Other')], default='general', max_length=30),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('job', 'Job'), ('grant', 'Grant')], max_length=20),
        ),
    ]
