# Generated by Django 5.2.4 on 2025-07-15 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('university', 'University'), ('college', 'College'), ('company', 'Company'), ('ngo', 'NGO')], default='university', max_length=50),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
